[font]
size = 10

[font.bold]
family = "PlemolJP Console NF"
style = "Bold"

[font.normal]
family = "PlemolJP Console NF"
style = "Regular"

[font.offset]
y = 1

[scrolling]
history = 10000
multiplier = 3

[window.dimensions]
columns = 200
lines = 60

[window.padding]
x = 8
y = 4
